name: Louis
description: Louis' not that secret hideout
meta_description: ""

aboutPage: true

highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://louis.gent'
google_analytics: 'UA-71606455-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Louis Van de Calseyde'
authorTwitter:  'vdclouis'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
